#!/usr/bin/env bash

# set the icon and a temporary location for the screenshot to be stored
#icon="$HOME/images/lock-icon-light.png"
#tmpbg='/tmp/screen.png'

# take a screenshot
#scrot "$tmpbg"

# blur the screenshot by resizing and scaling back up
#convert .config/i3/images/Bsodwindows10.png -filter Gaussian -thumbnail 20% -sample 500%  .config/i3/images/Bsodwindows10.png

# overlay the icon onto the screenshot
#mv convert filter .config/i3/images/Bsodwindows10.png  -gravity center -composite .config/i3/images/Bsodwindows10.png
# lock the screen with the blurred screenshot
i3lock -ute -i .config/i3/images/windows-blue-screen-of-death.png
